"""Add Vector to GQW_Vector table

Revision ID: 94e3710c81f0
Revises: 5bd505126a56
Create Date: 2026-06-10 13:07:45.211464

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94e3710c81f0'
down_revision: Union[str, None] = '5bd505126a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gqw_qualifications_id', table_name='gqw_qualifications')
    op.drop_table('gqw_qualifications')
    op.drop_index('ix_supervisor_department_id', table_name='supervisor_department')
    op.drop_table('supervisor_department')
    op.drop_index('ix_gqw_tags_id', table_name='gqw_tags')
    op.drop_table('gqw_tags')
    op.drop_index('ix_gqw_vectors_id', table_name='gqw_vectors')
    op.drop_table('gqw_vectors')
    op.drop_index('ix_supervisor_degree_id', table_name='supervisor_degree')
    op.drop_table('supervisor_degree')
    op.drop_index('ix_visitor_data_id', table_name='visitor_data')
    op.drop_index('ix_visitor_data_visitor_id', table_name='visitor_data')
    op.drop_table('visitor_data')
    op.drop_index('ix_gqw_data_id', table_name='gqw_data')
    op.drop_index('ix_gqw_data_theme', table_name='gqw_data')
    op.drop_table('gqw_data')
    op.drop_index('ix_gqw_supervisors_id', table_name='gqw_supervisors')
    op.drop_table('gqw_supervisors')
    op.drop_index('ix_pass_key_gqw_id', table_name='pass_key')
    op.drop_index('ix_pass_key_id', table_name='pass_key')
    op.drop_table('pass_key')
    op.drop_index('ix_model_tag_id', table_name='model_tag')
    op.drop_table('model_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vkr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tags_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tags_id'], ['gqw_tags.id'], name='model_tag_tags_id_fkey'),
    sa.ForeignKeyConstraint(['vkr_id'], ['gqw_data.id'], name='model_tag_vkr_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_tag_pkey')
    )
    op.create_index('ix_model_tag_id', 'model_tag', ['id'], unique=False)
    op.create_table('pass_key',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_encoded', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_get', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_expired', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gqw_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('visitor_f', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['visitor_f'], ['visitor_data.visitor_id'], name='pass_key_visitor_f_fkey'),
    sa.PrimaryKeyConstraint('id', name='pass_key_pkey')
    )
    op.create_index('ix_pass_key_id', 'pass_key', ['id'], unique=False)
    op.create_index('ix_pass_key_gqw_id', 'pass_key', ['gqw_id'], unique=False)
    op.create_table('gqw_supervisors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('degree_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['supervisor_degree.id'], name='gqw_supervisors_degree_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['supervisor_department.id'], name='gqw_supervisors_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gqw_supervisors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_gqw_supervisors_id', 'gqw_supervisors', ['id'], unique=False)
    op.create_table('gqw_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qualification_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('abstract', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['qualification_id'], ['gqw_qualifications.id'], name='gqw_data_qualification_id_fkey'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['gqw_supervisors.id'], name='gqw_data_supervisor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gqw_data_pkey')
    )
    op.create_index('ix_gqw_data_theme', 'gqw_data', ['theme'], unique=False)
    op.create_index('ix_gqw_data_id', 'gqw_data', ['id'], unique=False)
    op.create_table('visitor_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('visitor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('visitor_id', name='visitor_data_pkey')
    )
    op.create_index('ix_visitor_data_visitor_id', 'visitor_data', ['visitor_id'], unique=False)
    op.create_index('ix_visitor_data_id', 'visitor_data', ['id'], unique=False)
    op.create_table('supervisor_degree',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='supervisor_degree_pkey')
    )
    op.create_index('ix_supervisor_degree_id', 'supervisor_degree', ['id'], unique=False)
    op.create_table('gqw_vectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['gqw_tags.id'], name='gqw_vectors_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gqw_vectors_pkey')
    )
    op.create_index('ix_gqw_vectors_id', 'gqw_vectors', ['id'], unique=False)
    op.create_table('gqw_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gqw_tags_pkey')
    )
    op.create_index('ix_gqw_tags_id', 'gqw_tags', ['id'], unique=False)
    op.create_table('supervisor_department',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='supervisor_department_pkey')
    )
    op.create_index('ix_supervisor_department_id', 'supervisor_department', ['id'], unique=False)
    op.create_table('gqw_qualifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gqw_qualifications_pkey')
    )
    op.create_index('ix_gqw_qualifications_id', 'gqw_qualifications', ['id'], unique=False)
    # ### end Alembic commands ###
